### ISSUE TITLE
value of r in the GP.py code

### ISSUE THREAD

**Issue by thediffigral** [notsebastiano/GP_algorithm#1]
Hi Sir, 
I went through the grassburger procaccia algorithm. How did you take the input for this logarithmic_r function? & what is this factor? how to determine that? can you please help me out on this?

**Comment by ricardofrantz** [comment]
hey, any update here?

**Comment by notsebastiano** [comment]
Hi, this function is only necessary to generate a set of evenly spaced distances r that are used to estimate the fraction of points in the phase space that have a distance below this threshold r. It is estimated by first computing the standard deviation (std) of the original time series of scalars from which the phase space is reconstructed. A range of value starting from 0.1*std  to 0.7*std is used, but it can be changed to different ranges if you believe it's better for your analysis.

I have updated the code, added more comments and added a Notebook with an example of the implementation
